#!/bin/bash
# Script to fix AWS credentials issue on EC2

echo "=== Fixing AWS Credentials on EC2 ==="
echo ""
echo "SSH into the server with:"
echo "ssh -i amond.pem ec2-user@ec2-52-78-91-203.ap-northeast-2.compute.amazonaws.com"
echo ""
echo "Then run these commands:"
echo ""
echo "# 1. Navigate to backend directory"
echo "cd /home/ec2-user/amond/backend"
echo ""
echo "# 2. Check current environment variables"
echo "pm2 env backend | grep AWS"
echo ""
echo "# 3. If AWS variables are missing, restart PM2 with --update-env"
echo "pm2 restart backend --update-env"
echo ""
echo "# 4. Wait a few seconds and check again"
echo "sleep 5"
echo "pm2 env backend | grep AWS"
echo ""
echo "# 5. Check logs for confirmation"
echo "pm2 logs backend --lines 20 --nostream | grep 'AWS Environment Check'"
echo ""
echo "# 6. If still not working, try stopping and starting"
echo "pm2 stop backend"
echo "pm2 start app.ts --name backend --update-env"
echo "pm2 save"
echo ""
echo "# Alternative: Check if .env file has the variables"
echo "grep AWS .env"